### ISSUE TITLE
Remove our custom requirements

### ISSUE THREAD

**Issue by tkeemon** [appsembler/edx-platform#23]
We can remove this line:
https://github.com/appsembler/edx-platform/blob/04ecd3bb703bd089b0997f8fcdc80259f41daf80/requirements/edx/base.txt#L162-L163

and the associated appsembler.txt file from our fork of the edx-platform repo if we pull the contents from that file and add something to our server-vars.yml files like:

```
EDXAPP_EXTRA_REQUIREMENTS:
  - name: 'git+https://github.com/org/project@branch#egg=egg_name'
```

**Comment by natea** [comment]
@tkeemon this seems like a much cleaner way to do it. Keep as many changes in server-vars.yml as possible.

**Comment by OmarIthawi** [comment]
Thanks @tkeemon! It's been a long time since this issue was repored. I'll close it since I don't think we should remove the `appsembler.txt` file for the following reasons:

- It contains a minimal set of core requirements that are mandatory to the platform even in devstack e.g. `honeycomb`.
- It helps to reduce requirements duplication and share the core requirements in all of: `ansible`, Docker devstack images build process (no Ansible), regular `paver update_assets` in devstack.
- `server-vars.yml` contains a lot of non-core requirements and I think we have a good split at the moment
