### ISSUE TITLE
Generalize PR#83 and push upstream

### ISSUE THREAD

**Issue by tkeemon** [appsembler/edx-platform#88]
### [Allow importing arbitrary urlpatterns from Python modules](https://github.com/appsembler/edx-platform/pull/83)

- write tests
- reach out to edX and see if they're interested in this functionality
- generalize implementation

**Comment by bryanlandia** [comment]
Thanks @tkeemon .

**Comment by bryanlandia** [comment]
@tkeemon - I was just looking at edx/edx-platform HEAD and see that since Ginkgo edX has added a new app providing a plugin architecture for Django apps, which will automatically include urls, settings, signals from apps registered with either `lms.djangoapp` or `cms.djangoapp` entry point in setup.py.  Pretty cool, and looks like it will do away with the need for my `*_URLS_INCLUDE` approach.  I'm going to try cherrypicking the app into a Ficus install and see if we can do away with our special code.

cc @johnbaldwin @abeals

**Comment by bryanlandia** [comment]
There is a slight difference, in that we could conceivably just have a single module with some url patterns and import those, but in practice I think we've been including new ones from fully-fledged apps.  What do you think?

**Comment by OmarIthawi** [comment]
@bryanlandia I think it's too early (for Ficus and Ginkgo) to have the new `openedx.core.djangoapps.plugins` architecture.

In my opinion:
 - For Ficus we should stick to `*_URLS_INCLUDE`. 
 - For Ginkgo, if we'd like to backport `openedx.core.djangoapps.plugins` we should do that upstream first, simply to get better reviews for such big feature.
 - Or we could wait for Hawthorne, since we'll get it there anyway.

**Comment by OmarIthawi** [comment]
Not really needed by the addition of `openedx.core.djangoapps.plugins` from Open edX in Hawthorn+.
